name: Greeting on variable day

on:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - 'start'
  watch:
    types: [started]

env:
  DAY_OF_WEEK: Monday
  DATE: $(date +'%Y-%m-%d')
  
  
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: |
          source "${GITHUB_WORKSPACE}/settings.ini"
          echo REPO_URL
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
          #a = $(date +'%Y-%m-%d')
        env:
          First_Name: ${REPO_URL}
          
      - name: test
        run: |
          echo ${{ env.DATE }}
          echo ${{ env.First_Name }}
          #echo $a
