name: Openwrt-AutoBuild

on:
#  release:
#    types: [published]
  push:
    branches:
      - master
    paths:
      - 'start'
  watch:
    types: [started]

env:
  DATE: $(date +'%Y-%m-%d')

jobs:
  build:
    runs-on:  ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    name: Build ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [lean-minimal-x64,lean-complete-x64]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Load Settings.ini
      run: |    
        source "${GITHUB_WORKSPACE}/settings.ini"
        echo "REPO_URL=${REPO_URL}" >> $GITHUB_ENV
    - name: test
      run: |
        echo $${env.REPO_URL}
