name: Greeting on variable day

on:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - 'start'
  watch:
    types: [started]

env:
  DAY_OF_WEEK: Monday
  DATE: $(date +'%Y-%m-%d')
  
  
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: |
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
      - name: test
        run: |
          echo $date
